defaults:
  - _self_
  - optimizer: qt
  - user_groups: p50

seed: 42
qor_target: 0.6

requests_dataset: normal_requests     #"normal_requests", "static_requests", "synthetic_requests"
region: CA-ON

vp: 1 # validity period duration

model_qualities:
  - tier_0
  - tier_1
  - tier_2
  - tier_3
  - tier_4

machines:
  - _target_: src.scenario.Machine
    name: AWS_p4d.24xlarge
    power_usage: 3.7818             # 3,781.8 W
    idle_power_usage: 0.7448  # kW for AWS p4d (8xA100-SXM4-80GB)
    pue: 1
    performance:
      tier_0: 36792     # 10.22 rps
      tier_1: 46800     # 13 rps
      tier_2: 27288     # 7.58 rps
      tier_3: 18000     # 4–6 rps → midpoint 5.0
      tier_4: 37368     # 10.38 rps
    embedded_carbon: 135.3  # gCO2e/h
  - _target_: src.scenario.Machine
    name: AWS_p5.48xlarge
    power_usage: 6.26               # 6,260 W
    idle_power_usage: 1.15        # kW 
    pue: 1
    performance:
      tier_0: 86292     # 23.97 rps
      tier_1: 95292    # 26.47 rps
      tier_2: 38556     # 10.71 rps
      tier_3: 34632     # 9.62 rps
      tier_4: 52308     # 14.53 rps
    embedded_carbon: 273
  - _target_: src.scenario.Machine
    name: AWS_p6-b200.48xlarge
    power_usage: 8.8                # 8,800 W
    idle_power_usage: 1.475        # kW 
    pue: 1
    performance:
      tier_0: 144000    # 35–45 rps → midpoint 40
      tier_1: 160776    # 44.66 rps
      tier_2: 99000     # 25–30 rps → midpoint 27.5
      tier_3: 81000     # 20–25 rps → midpoint 22.5
      tier_4: 115200    # 32 rps
    embedded_carbon: 508

result_dir: results
